config/routes.rb
Cms::Application.routes.draw do
  root 'application#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  if ENV['LOADERIO_VERIFICATION_TOKEN']
    get ENV['LOADERIO_VERIFICATION_TOKEN'], to: 'loaderios#show'
  end

  if ENV['TEST_ROUTES']
    get 'timeout', to: 'test_routes#timeout'
  end

  resource :account, only: [:edit, :update] do
    get :sites
  end

  resource :health, only: [:show]

  resource :robots, only: [:show]

  resource :site, only: [:edit, :update] do
    match :css, via: [:get, :patch]

    resources :images, only: [:index]
    resources :messages, only: [:index, :show]
    resources :users, only: [:index]
  end

  resource :sitemap, only: [:show]

  resources :stylesheets, only: [:show]

  resources :pages, path: '', only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post :contact_form
    end
  end

  match '*path', to: 'application#page_not_found', via: :all
end

app/models/message.rb
class Message
  include CouchModel

  property :site_id, type: String
  property :subject, type: String
  property :name, type: String
  property :email_address, type: String
  property :phone_number, type: String
  property :delivered, type: :boolean, default: false

  auto_strip_attributes *property_names, squish: true

  property :message, type: String

  attr_accessor :do_not_fill_in
  attr_accessor :site

  set_callback :validate, :before do
    self.site_id = site.id if site
  end

  validates *property_names, no_html: true

  validates :site_id,
    presence: true

  validates :subject,
    presence: true

  validates :name,
    presence: true,
    length: {maximum: 64}

  validates :email_address,
    presence: true,
    length: {maximum: 64},
    email_format: true

  validates :phone_number,
    length: {maximum: 32}

  validates :message,
    presence: true,
    length: {maximum: 2048}

  validates :do_not_fill_in,
    length: {maximum: 0}

  validate do
    text = message.to_s.downcase

    [
      'facebook followers',
      'facebook likes',
      'facebook page likes',
      'facebook visitors',
      'search engine',
    ].each do |spam_text|
      errors.add(:message, :spam) if text.include? spam_text
    end
  end

  view :by_site_id_and_created_at,
    key: [:site_id, :created_at]

  view :by_site_id_and_id,
    key: [:site_id, :_id]

  def self.find_by_site_and_id(site, id)
    CouchPotato.database.first(by_site_id_and_id(key: [site.id, id]))
  end

  def self.find_all_by_site(site)
    CouchPotato.database.view(
      by_site_id_and_created_at(startkey: [site.id], endkey: [site.id, {}])
    ).reverse
  end

  def deliver
    MessageMailer.new_message(self).deliver
    self.delivered = true
    self.save!
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :login_required

  def index
    @messages = Message.find_all_by_site(@site)
  end

  def show
    @message = Message.find_by_site_and_id(@site, params[:id])
    return page_not_found unless @message
  end
end

app/views/messages/index.html.haml
- content_for :title, t('.title')
- content_for :page_icon, t('.icon')

%table.table.table-bordered
  %thead
    %tr
      %th= Message.human_attribute_name(:created_at)
      %th= Message.human_attribute_name(:name)
      %th= Message.human_attribute_name(:email_address)

  %tbody
    - @messages.each do |message|
      %tr
        %td= link_to(timeago_tag(message.created_at, force: true), site_message_path(message))
        %td= link_to(message.name, site_message_path(message))
        %td= link_to(message.email_address, site_message_path(message))

app/views/messages/show.html.haml
- content_for :title, t('.title')
- content_for :page_icon, t('.icon')

%dl.dl-horizontal
  %dt= Message.human_attribute_name(:created_at)
  %dd= timeago_tag(@message.created_at, force: true)

  %dt= Message.human_attribute_name(:name)
  %dd= @message.name

  %dt= Message.human_attribute_name(:email_address)
  %dd= @message.email_address

  - unless @message.phone_number.blank?
    %dt= Message.human_attribute_name(:phone_number)
    %dd= @message.phone_number

  %dt= Message.human_attribute_name(:message)
  %dd
    - @message.message.split("\n").each do |line|
      = line
      %br