config/routes.rb
Cms::Application.routes.draw do
  root 'application#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  if ENV['LOADERIO_VERIFICATION_TOKEN']
    get ENV['LOADERIO_VERIFICATION_TOKEN'], to: 'loaderios#show'
  end

  if ENV['TEST_ROUTES']
    get 'timeout', to: 'test_routes#timeout'
  end

  resource :account, only: [:edit, :update] do
    get :sites
  end

  resource :health, only: [:show]

  resource :robots, only: [:show]

  resource :site, only: [:edit, :update] do
    match :css, via: [:get, :patch]

    resources :images, only: [:index]
    resources :messages, only: [:index, :show]
    resources :users, only: [:index]
  end

  resource :sitemap, only: [:show]

  resources :stylesheets, only: [:show]

  resources :pages, path: '', only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post :contact_form
    end
  end

  match '*path', to: 'application#page_not_found', via: :all
end

app/views/pages/_contact_form.html.haml
= simple_form_for (@message || Message.new), url: contact_form_page_path do |form|
  = form.input :name
  = form.input :email_address
  = form.input :phone_number
  = form.input :message, as: :text, input_html: {rows: 4, class: 'input-block-level autogrow'}

  .hidden
    = form.input :do_not_fill_in

  .form-actions
    = form.button :submit, t('actions.send_message')

app/views/pages/_form.html.haml
= simple_form_for @page do |form|
  = form.input :name, autofocus: true
  = form.input :private, as: :boolean

  .tinymce{:id => 'page[html_content]'}
    = form.object.html_content.to_s.html_safe

  .form-actions
    = form.button :submit
    = link_to t('actions.cancel'), @page, class: 'btn'

= tinymce

app/views/pages/edit.html.haml
- content_for :title, t('.title', name: @page.name)
- content_for :page_icon, t('.icon')

- content_for :body_id, "page_url_#{@page.url}"

= render 'form'

app/views/pages/new.html.haml
- content_for :title, t('.title')
- content_for :page_icon, t('.icon')

- content_for :body_id, 'page_url_new'

= render 'form'

app/views/pages/show.html.haml
- content_for :title, @page.name unless @page.url == 'home'

- if @page.private
  - content_for :page_icon, t('.private.icon')

- content_for :body_id, "page_url_#{@page.url}"

= @page.html_content.html_safe if @page.html_content

= render @page.bottom_section if @page.bottom_section