config/routes.rb
Cms::Application.routes.draw do
  root 'application#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  if ENV['LOADERIO_VERIFICATION_TOKEN']
    get ENV['LOADERIO_VERIFICATION_TOKEN'], to: 'loaderios#show'
  end

  if ENV['TEST_ROUTES']
    get 'timeout', to: 'test_routes#timeout'
  end

  resource :account, only: [:edit, :update] do
    get :sites
  end

  resource :health, only: [:show]

  resource :robots, only: [:show]

  resource :site, only: [:edit, :update] do
    match :css, via: [:get, :patch]

    resources :images, only: [:index]
    resources :messages, only: [:index, :show]
    resources :users, only: [:index]
  end

  resource :sitemap, only: [:show]

  resources :stylesheets, only: [:show]

  resources :pages, path: '', only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post :contact_form
    end
  end

  match '*path', to: 'application#page_not_found', via: :all
end

app/views/layouts/_footer.html.haml
%footer#page_footer.dontprint
  %ul.unstyled
    - if @page and @page.persisted?
      %li#last_update= t('.last_updated', updated_at: timeago_tag(@page.updated_at, force: true)).html_safe

    %li#copyright= footer_copyright

    %li
      %ul#footer_links.unstyled
        %li= link_to t('sitemaps.show.title'), sitemap_path

        - if authenticated?
          %li= link_to t('sessions.destroy.title'), logout_path
        - else
          %li= link_to t('sessions.new.title'), login_path

app/views/layouts/_header.html.haml
%header#page_header.dontprint
  %h1#site_name
    = link_to page_path('home') do
      - if @site.header_image_filename
        = image_tag(@site.header_image.span12.url, alt: @site.name)
      - else
        = @site.name

  - unless @site.sub_title.blank?
    %h2#site_sub_title= @site.sub_title

app/views/layouts/_main_article.html.haml
%article#main_article
  #content
    - if content_for?(:title)
      %header
        %h1
          = glyph(content_for(:page_icon)) if content_for(:page_icon)
          = content_for(:title)

    = bootstrap_flash
    = yield

app/views/layouts/_main_menu.html.haml
- unless @site.main_menu.blank?
  #main_menu.dontprint
    = nav_bar do
      = menu_group do
        - @site.main_menu.each do |link|
          = menu_item link["text"], link["url"]

app/views/layouts/_sidebar.html.haml
%aside#sidebar.dontprint= @site.sidebar_html_content.html_safe

app/views/layouts/_topbar.html.haml
#topbar.dontprint
  = nav_bar brand: @site.name, brand_link: root_path, fixed: :top, inverse: true, responsive: true, fluid: true do
    = menu_group pull: :right do
      = menu_text image_tag(user.gravatar_url, alt: 'Profile Image', class: 'profile_image img-circle')

    = menu_group pull: :right do
      = drop_down Page.model_name.human do
        - if @page and @page.persisted?
          = menu_item edit_page_path(@page.url) do
            = glyph(t('pages.edit.icon'))
            = t('actions.edit')

          = menu_item glyph(t('pages.delete.icon')) + " " + t('actions.delete'),
                       page_path(@page.url),
                       method: :delete,
                       data: {confirm: t('pages.delete.text', name: @page.name)},
                       "data-confirm-title" => "<i class='icon-trash'></i> #{t('pages.delete.title')}".html_safe,
                       "data-confirm-proceed" => "<i class='icon-trash'></i> #{t('actions.delete')}".html_safe,
                       "data-confirm-cancel" => "<i class='icon-remove'></i> #{t('actions.cancel')}".html_safe,
                       "data-confirm-proceed-class" => "btn-danger"

        = menu_item new_page_path do
          = glyph(t('pages.new.icon'))
          = t('pages.new.title')

      = drop_down Site.model_name.human do
        = menu_item site_messages_path do
          = glyph(t('messages.index.icon'))
          = t('messages.index.title')

        = menu_item site_images_path do
          = glyph(t('images.index.icon'))
          = t('images.index.title')

        = menu_item edit_site_path do
          = glyph(t('sites.edit.icon'))
          = t('sites.edit.title')

        = menu_item site_users_path do
          = glyph(t('users.index.icon'))
          = t('users.index.title')

        - if feature.edit_css
          = menu_item css_site_path do
            = glyph(t('sites.css.icon'))
            = t('sites.css.title')

        = menu_item sitemap_path do
          = glyph(t('sitemaps.show.icon'))
          = t('sitemaps.show.title')

      = drop_down user.email do
        = menu_item edit_account_path do
          = glyph(t('accounts.edit.icon'))
          = t('accounts.edit.title')

        - if user.sites.size > 1
          = menu_item sites_account_path do
            = glyph(t('accounts.sites.icon'))
            = t('accounts.sites.title')

        = menu_item logout_path do
          = glyph(t('sessions.destroy.icon'))
          = t('sessions.destroy.title')

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title= page_title(content_for(:title))
    /[if lt IE 9]
      %script{src: '//html5shiv.googlecode.com/svn/trunk/html5.js'}
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag @site.css_filename, media: 'all' if @site.css_filename
    = javascript_include_tag 'application'
    = analytics_init(tracker: @site.google_analytics, domain: @site.host) if @site.google_analytics
    = csrf_meta_tag

  %body{id: (content_for(:body_id) if content_for?(:body_id))}
    = render 'layouts/topbar' if authenticated?
    = render "layouts/pages/#{@site.layout}"